import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/appHeader/Navbar";
import Banner from "@/components/appHeader/Banner";
import SubMenu from "@/components/appHeader/SubMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner></Banner>
        <Navbar></Navbar>
        <SubMenu></SubMenu>
        {children}
      </body>
    </html>
  );
}
